### ISSUE TITLE
OpenVR System not found.

### ISSUE THREAD

**Issue by scslayerage** [Hotrian/HeadlessOverlayToolkit#3]
I always get that error immediately at opening the application. I have a Twitch chat on my screen when VR opens, but it is small and fixed in the world rather than following my left controller. It's pretty hard to read.

I've checked the log file - it doesn't have "Connect to VR Server Failed (301)", and I've tried running as administrator but that didn't work. I'll include the log.
[output_log.txt](https://github.com/Hotrian/HeadlessOverlayToolkit/files/430727/output_log.txt)

**Comment by Hotrian** [comment]
This likely isn't an issue I can fix as it's an issue where your Unity can't connect to OpenVR for whatever reason. Any time this has happened to me I have fixed it by restating SteamVR/Unity/My PC. What version of Unity are you running? This code is meant for 5.3.5f1. 5.4+ breaks Utility Applications because Unity always conncets to OpenVR as an actual Application and not a Utility or Overlay application.

Since this issue is on the HOTK source, and it hasn't been updated in a while, it's possible SteamVR was updated beyond HOTK, in which case it would be an issue I could fix. I don't believe this to be the case, however.

Can you try my program [OpenVRDesktopDisplayPortal](https://github.com/Hotrian/OpenVRDesktopDisplayPortal)? It uses an advanced version of the HOTK code. I work with it almost daily and I am certain OVRDDP connects to the latest SteamVR Beta without issue.

Did you place this issue on the correct repo? You say 

> I have a Twitch chat on my screen when VR opens

Which leads me to believe this belongs on [OpenVRTwitchChat](https://github.com/Hotrian/OpenVRTwitchChat).

**Comment by Hotrian** [comment]
My bad. Just rechecked your log file and realized it says

> C:\Users\Cody Adair\Desktop\**OpenVRTwitchChat-v1.0.7.1-beta.Experimental**\OpenVRTwitchChat-v1.0.7.1-beta (Experimental)_Data\Managed\

So you did post this issue on the wrong repo as this belongs on OVRTC, which is actually a project I intend to drop and merge into OVRDDP.

Can you try using the latest release of OVRDDP just to see if it works? Something might have broken between the latest release of OVRTC and now, but I'm pretty sure nothing changed that should have broken the connection to SteamVR.

If OVRDDP works, you can open the Popout chat on Twitch and clone that into a VR Overlay. I know it's not the same thing, but at least it works.

**Comment by Hotrian** [comment]
Reading over this all again, I realized your log file says

> Connected to lighthouse:LHR-F0CDB471

Which means it is connecting to OpenVR without issue. The OpenVRTwitchChat log files are not entirely helpful because most of the output is being redirected to the display. OpenVRDesktopDisplayPortal is much more useful for debugging because it writes all of it's output information to the log file. Is OVRTC spamming "OpenVR System not found." to the display?

Why did you specifically mention "Connect to VR Server Failed (301)"? Is this an error you encounter often? I think there might be an issue with your SteamVR installation if you commonly encounter this issue.

**Edit:**

> I have a Twitch chat on my screen when VR opens, but it is small and fixed in the world rather than following my left controller. 

Could it be that you simply didn't select a controller in the bottom left? This is referred to as "Anchor Point" in [this graphic](https://camo.githubusercontent.com/544e1fa7f28bc92fee5b13b0e4f0e8f474ebb646/687474703a2f2f696d6167652e70726e747363722e636f6d2f696d6167652f32323463626431346430326634653230393837396566396435663634376265322e706e67). If a controller is detected it _should_ automatically attach to it, but perhaps it has attached to Screen or World instead?

**Comment by Hotrian** [comment]
It's been six weeks now and you never replied :(. Did you ever fix this issue?

I'm going to close this soon if you don't reply.
